version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: testDb
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: